import { Platform, ContentType, ContentGoal, Tone, PostLength } from '@/types/database';

export const THAI_PLATFORM_LABELS: Record<Platform, string> = {
  facebook: 'เฟซบุ๊ก (Facebook)',
  instagram: 'อินสตาแกรม (Instagram)',
  line_oa: 'ไลน์ (LINE OA - Broadcast)',
  line_voom: 'ไลน์ วูม (LINE VOOM)',
  tiktok: 'ติ๊กต็อก (TikTok)',
  google_business: 'กูเกิล บิสเนส (Google Business)',
  website: 'เว็บไซต์ (Website)',
  other: 'สื่ออื่น ๆ',
};

export const THAI_CONTENT_TYPE_LABELS: Record<ContentType, string> = {
  promotion_post: 'โพสต์โปรโมชั่น',
  educational_post: 'โพสต์ให้ความรู้',
  before_after_post: 'โพสต์ รีวิว Before/After',
  testimonial_post: 'โพสต์รีวิวจากลูกค้า',
  faq_content: 'เนื้อหา FAQ',
  review_reply: 'ตอบกลับรีวิว',
  seo_snippet: 'ชุดข้อมูล SEO',
  blog_idea: 'ไอเดียบล็อก',
  blog_outline: 'โครงร่างบล็อก',
  service_page_draft: 'ร่างหน้าบริการ',
  campaign_idea: 'ไอเดียแคมเปญ',
  broadcast_message: 'ข้อความบรอดแคสต์',
  short_video_script: 'บทวิดีโอสั้น',
  offer_announcement: 'ประกาศข้อเสนอพิเศษ',
  seasonal_campaign: 'แคมเปญตามฤดูกาล',
  customer_reminder: 'ข้อความแจ้งเตือนลูกค้า',
  trust_building_post: 'โพสต์สร้างความน่าเชื่อถือ',
  local_area_post: 'โพสต์การตลาดเฉพาะพื้นที่',
};

export const THAI_CONTENT_GOAL_LABELS: Record<ContentGoal, string> = {
  lead_generation: 'หาลูกค้าใหม่ (Leads)',
  awareness: 'สร้างการรับรู้ (Awareness)',
  reactivation: 'ดึงลูกค้าเก่ากลับมา (Reactivation)',
  trust_building: 'สร้างความเชื่อมั่น (Trust)',
  promotions: 'กระตุ้นยอดขาย (Promotions)',
  local_seo: 'ทำอันดับในพื้นที่ (Local SEO)',
  customer_education: 'ให้ความรู้ลูกค้า',
  repeat_service_reminder: 'แจ้งเตือนใช้บริการซ้ำ',
  testimonial_amplification: 'ขยายผลรีวิวลูกค้า',
};

export const THAI_TONE_LABELS: Record<Tone, string> = {
  professional: 'เป็นทางการ (Professional)',
  friendly: 'เป็นกันเอง (Friendly)',
  casual: 'ชิลล์ๆ (Casual)',
  urgent: 'เร่งด่วน (Urgent)',
  authoritative: 'น่าเชื่อถือ (Authoritative)',
  empathetic: 'เข้าใจลูกค้า (Empathetic)',
  enthusiastic: 'กระตือรือร้น (Enthusiastic)',
  educational: 'เชิงสอน (Educational)',
};

export const THAI_LENGTH_LABELS: Record<PostLength, string> = {
  short: 'สั้น (Short)',
  medium: 'ปานกลาง (Medium)',
  long: 'ยาว (Long)',
};

export const THAI_UI_LABELS = {
  content_details: 'รายละเอียดเนื้อหา',
  service_type: 'ประเภทบริการ',
  topic: 'หัวข้อ / เรื่อง',
  pain_point: 'ปัญหาของลูกค้า (Pain Point)',
  location: 'ทำเล / พื้นที่ให้บริการ',
  promotion_offer: 'โปรโมชั่น / ข้อเสนอ',
  target_audience: 'กลุ่มเป้าหมาย',
  cta_style: 'รูปแบบ CTA',
  keyword: 'คีย์เวิร์ดที่ต้องการใส่',
  custom_notes: 'บันทึกเพิ่มเติม',
  assign_campaign: 'มอบหมายให้แคมเปญ',
  no_campaign: 'ไม่ระบุแคมเปญ',
  auto: 'อัตโนมัติ (Auto)',
  generated_content: 'คอนเทนต์ที่สร้างขึ้น',
  title: 'หัวข้อ (Title)',
  opening_hook: 'ประโยคเปิด (Opening Hook)',
  content_body: 'เนื้อหา (Body)',
  short: 'แบบสั้น',
  medium: 'แบบกลาง',
  long: 'แบบยาว',
  body: 'เนื้อหาหลัก',
  cta: 'คำเชิญชวน (CTA)',
  message_body: 'เนื้อหาข้อความ',
  compact_version: 'รุ่นกะทัดรัด',
  button_text: 'ข้อความบนปุ่ม',
  urgency: 'ระดับความเร่งด่วน',
  personalization: 'ข้อเสนอแนะรายบุคคล',
  hook_3s: 'ฮุค 3 วินาที',
  script_outline: 'โครงร่างบท (Outline)',
  scene_flow: 'ลำดับฉาก (Scene Flow)',
  seo_title: 'SEO Title',
  meta_description: 'Meta Description',
  intro_paragraph: 'ย่อหน้านำ',
  service_description: 'รายละเอียดบริการ',
  trust_section: 'ส่วนสร้างความเชื่อมั่น',
  h2_sections: 'หัวข้อย่อย (H2)',
  faq_section: 'คำถามที่พบบ่อย (FAQ)',
  carousel_slides: 'ภาพสไลด์ (Carousel)',
  on_image_text: 'ข้อความในภาพ',
  metadata: 'ข้อมูลเมตา (Metadata)',
  variations: 'ฉบับเลือกอื่น ๆ',
  suggested_comments: 'ความคิดเห็นแนะนำ',
  platform_package: 'ชุดคอนเทนต์รวมแพลตฟอร์ม',
  facebook_version: 'ฉบับ Facebook',
  line_oa_version: 'ฉบับ LINE OA',
  instagram_version: 'ฉบับ Instagram',
  line_voom_version: 'ฉบับ LINE VOOM',
  google_business_version: 'ฉบับ Google Business',
  tiktok_version: 'ฉบับ TikTok',
  first_comment: 'ความคิดเห็นแรก (First Comment)',
  content_angle: 'มุมมองเนื้อหา (Content Angle)',
  post_type: 'ประเภทโพสต์',
  seo_keywords: 'คีย์เวิร์ด SEO',
  service_areas_list: 'พื้นที่บริการที่ระบุ',
  headline: 'พาดหัว (Headline)',
  caption_main: 'เนื้อหาหลัก (Caption Main)',
  caption_short: 'เนื้อหาแบบสั้น (Caption Short)',
  hashtags: 'แฮชแท็ก (#Hashtags)',
  scene: 'ฉากที่',
  on_screen: 'ข้อความบนจอ',
  business_profile: 'ข้อมูลธุรกิจ',
  business_profile_desc: 'ตั้งค่ารายละเอียดธุรกิจของคุณเพื่อปรับแต่งเนื้อหาที่สร้างขึ้นให้เหมาะสมที่สุด',
  basic_info: 'ข้อมูลพื้นฐาน',
  business_name_label: 'ชื่อธุรกิจ *',
  business_type_label: 'ประเภทธุรกิจ',
  company_description: 'รายละเอียดบริษัท/ธุรกิจ',
  company_desc_placeholder: 'อธิบายธุรกิจของคุณสั้น ๆ...',
  services_coverage: 'บริการและพื้นที่ให้บริการ',
  service_categories_label: 'หมวดหมู่งานบริการ',
  service_areas_label: 'พื้นที่ให้บริการ',
  brand_tone: 'แบรนด์และโทนการสื่อสาร',
  tone_voice_label: 'โทนเสียงของแบรนด์',
  brand_style_label: 'สไตล์ของแบรนด์',
  brand_keywords_label: 'คีย์เวิร์ดประจำแบรนด์',
  banned_words_label: 'คำที่ห้ามใช้',
  target_pain_points: 'กลุ่มเป้าหมายและปัญหาของลูกค้า',
  common_pain_points: 'ปัญหาที่ลูกค้ามักพบเจอ (Pain Points)',
  trust_ctas: 'จุดเด่นและคำเชิญชวน (CTA)',
  trust_signals_label: 'จุดเด่น/ความน่าเชื่อถือ',
  promotion_goals_label: 'เป้าหมายการโปรโมท',
  default_ctas_label: 'CTA เริ่มต้น',
  contact_info: 'ข้อมูลการติดต่อ',
  phone_label: 'เบอร์โทรศัพท์',
  email_label: 'อีเมลติดต่อ',
  line_id_label: 'ไอดีไลน์',
  website_url_label: 'เว็บไซต์',
  facebook_url_label: 'ลิงก์หน้าเฟซบุ๊ก',
  language_settings: 'การตั้งค่าภาษา',
  default_lang_label: 'ภาษาหลัก',
  bilingual_mode: 'เปิดใช้งานโหมดสองภาษา (ไทย + อังกฤษ)',
  faq_base: 'ฐานข้อมูลคำถามที่พบบ่อย (FAQ)',
  add_faq: 'เพิ่ม FAQ',
  save_profile: 'บันทึกโปรไฟล์',
  saving: 'กำลังบันทึก...',
  loading_profile: 'กำลังโหลดข้อมูลโปรไฟล์...',
  dashboard: 'แดชบอร์ด',
  content_library: 'คลังเนื้อหา',
  campaign_workspace: 'พื้นที่จัดการแคมเปญ',
  settings: 'ตั้งค่า',
  ai_creator: 'สร้างคอนเทนต์ด้วย AI',
  dashboard_overview: 'ภาพรวมการสร้างคอนเทนต์ของคุณ',
  upload_image_title: 'อัปโหลดรูปภาพ (AI จะคิดคอนเทนต์จากรูป)',
  upload_image_btn: 'อัปโหลดรูปภาพ (ประกอบการสร้าง)',
  image_analysis_in_progress: 'กำลังวิเคราะห์รูปภาพของคุณ...',
  generate_content_btn: 'สร้างคอนเทนต์',
  total_contents: 'คอนเทนต์ทั้งหมด',
  last_7_days: '7 วันที่ผ่านมา',
  platforms_used: 'แพลตฟอร์มที่ใช้',
  recent_content: 'คอนเทนต์ล่าสุด',
  view_all: 'ดูทั้งหมด',
  by_platform: 'แยกตามแพลตฟอร์ม',
  quick_actions: 'ทางลัด',
  facebook_post: 'โพสต์ Facebook',
  instagram_post: 'โพสต์ Instagram',
  line_broadcast: 'บรอดแคสต์ LINE',
  tiktok_script: 'บท TikTok',
  service_page: 'หน้าหลักบริการ',
  new_campaign: 'แคมเปญใหม่',
  welcome_title: 'ยินดีต้อนรับสู่ AI Content Studio',
  welcome_desc: 'เริ่มต้นด้วยการตั้งค่าข้อมูลธุรกิจของคุณเพื่อสร้างคอนเทนต์การตลาด',
  create_profile_btn: 'สร้างข้อมูลธุรกิจ',
  loading_dashboard: 'กำลังโหลดแดชบอร์ด...',
  no_content_yet: 'ยังไม่มีคอนเทนต์ที่สร้างขึ้น เริ่มสร้างกันเลย!',
  no_data_yet: 'ยังไม่มีข้อมูล',
  content_items_count: 'รายการคอนเทนต์ที่สร้าง',
  generate_new: 'สร้างคอนเทนต์ใหม่',
  search_placeholder: 'ค้นหาตามหัวข้อหรือบริการ...',
  all_platforms: 'ทุกแพลตฟอร์ม',
  all_types: 'ทุกประเภท',
  loading_content: 'กำลังโหลดคอนเทนต์...',
  no_content_found: 'ไม่พบคอนเทนต์',
  adjust_filters: 'ลองปรับการค้นหาหรือตัวกรองของคุณ',
  start_generating_desc: 'เริ่มต้นสร้างคอนเทนต์การตลาดสำหรับธุรกิจของคุณ',
  view_btn: 'ดู',
  copy_btn: 'คัดลอก',
  archive_btn: 'เก็บถาวร',
  delete_btn: 'ลบ',
  previous_btn: 'หน้าก่อนหน้า',
  next_btn: 'ถัดไป',
  page_info: 'หน้า {page} จาก {total}',
  content_preview: 'ตัวอย่างคอนเทนต์',
  content_deleted: 'ลบคอนเทนต์เรียบร้อยแล้ว',
  content_archived: 'เก็บถาวรคอนเทนต์เรียบร้อยแล้ว',
  copied_to_clipboard: 'คัดลอกไปยังคลิปบอร์ดแล้ว',
  failed_to_load: 'โหลดข้อมูลไม่สำเร็จ',
  failed_to_delete: 'ลบไม่สำเร็จ',
  failed_to_archive: 'เก็บถาวรไม่สำเร็จ',
  campaign_desc: 'จัดการคอนเทนต์ของคุณแยกตามแคมเปญการตลาด',
  no_campaigns: 'ยังไม่มีแคมเปญ',
  create_first_campaign: 'สร้างแคมเปญแรกของคุณเพื่อจัดระเบียบคอนเทนต์ที่สร้างขึ้น',
  create_campaign_btn: 'สร้างแคมเปญ',
  status_active: 'กำลังใช้งาน',
  status_paused: 'พักชั่วคราว',
  status_completed: 'เสร็จสิ้น',
  status_archived: 'เก็บถาวร',
  no_content_in_campaign: 'ยังไม่มีคอนเทนต์ในแคมเปญนี้',
  generate_for_campaign: 'สร้างคอนเทนต์สำหรับแคมเปญนี้',
  generate_more_content: 'สร้างคอนเทนต์เพิ่มเติม',
  edit_campaign: 'แก้ไขแคมเปญ',
  campaign_name_label: 'ชื่อแคมเปญ *',
  campaign_desc_label: 'คำอธิบาย',
  campaign_type_label: 'ประเภทแคมเปญ',
  saving_btn: 'กำลังบันทึก...',
  update_btn: 'อัปเดต',
  create_btn: 'สร้าง',
  cancel_btn: 'ยกเลิก',
  campaign_name_required: 'กรุณาระบุชื่อแคมเปญ',
  campaign_updated: 'อัปเดตแคมเปญเรียบร้อยแล้ว',
  campaign_created: 'สร้างแคมเปญเรียบร้อยแล้ว',
  campaign_deleted: 'ลบแคมเปญเรียบร้อยแล้ว',
  failed_to_update_status: 'อัปเดตสถานะไม่สำเร็จ',
  loading_campaigns: 'กำลังโหลดแคมเปญ...',
  settings_desc: 'จัดการค่าเริ่มต้นสำหรับการสร้างคอนเทนต์',
  tone_presets: 'โทนเสียง',
  cta_presets: 'คำกระตุ้นการตัดสินใจ (CTA)',
  platform_presets: 'ค่าเริ่มต้นแพลตฟอร์ม',
  prompt_presets: 'พรอมต์เริ่มต้น',
  add_tone_preset: 'เพิ่มโทนเสียง',
  add_cta_preset: 'เพิ่ม CTA',
  add_platform_preset: 'เพิ่มแพลตฟอร์ม',
  add_prompt_preset: 'เพิ่มพรอมต์',
  no_tone_presets: 'ยังไม่มีโทนเสียง',
  no_cta_presets: 'ยังไม่มี CTA',
  no_platform_presets: 'ยังไม่มีแพลตฟอร์ม',
  no_prompt_presets: 'ยังไม่มีพรอมต์',
  default_badge: 'เริ่มต้น',
  edit_preset: 'แก้ไขค่าเริ่มต้น',
  new_preset: 'สร้างค่าเริ่มต้นใหม่',
  loading_settings: 'กำลังโหลดการตั้งค่า...',
  save_btn: 'บันทึก',
  deleted_success: 'ลบเรียบร้อยแล้ว',
  preset_updated: 'อัปเดตค่าเริ่มต้นเรียบร้อยแล้ว',
  preset_created: 'สร้างค่าเริ่มต้นเรียบร้อยแล้ว',
  failed_to_delete_preset: 'ลบไม่สำเร็จ',
  failed_to_save_preset: 'บันทึกไม่สำเร็จ',
  suggested_comments_desc: 'AI สร้างคอมเมนต์สำหรับโพสต์ลงในโพสต์ของคุณ',
  auto_post: 'โพสต์อัตโนมัติ',
  auto_post_btn: 'โพสต์ไปยังเพจ',
  posting_in_progress: 'กำลังโพสต์...',
  post_success: 'โพสต์สำเร็จแล้ว!',
  post_failed: 'โพสต์ไม่สำเร็จ',
  select_pages: 'เลือกเพจที่ต้องการโพสต์',
  post_with_image: 'โพสต์พร้อมรูปภาพ',
  comments_will_be_posted: 'คอมเมนต์แนะนำจะถูกโพสต์อัตโนมัติ',
  copy_comment: 'คัดลอกคอมเมนต์',
  ai_chat: 'AI ผู้ช่วยอัจฉริยะ',
  chat_placeholder: 'พิมพ์ข้อความถาม AI ที่นี่...',
  clear_chat: 'ล้างบทสนทนา',
  chat_processing: 'AI กำลังประมวลผล...',
  chat_welcome: 'สวัสดีครับ! ผมเป็น AI ผู้ช่วยส่วนตัวของคุณ มีอะไรให้ผมช่วยแนะนำหรือช่วยเขียน Content ในวันนี้ไหมครับ?',
};
